"""
Módulo de configuração.
"""
from .settings import (
    TELEGRAM_TOKEN,
    OLLAMA_MODEL,
    EMBEDDING_MODEL,
    LLM_REQUEST_TIMEOUT,
    LLM_TEMPERATURE,
    LLM_CONTEXT_WINDOW,
    LLM_NUM_CTX,
    SIMILARITY_TOP_K,
    SIMILARITY_CUTOFF,
    QUERY_TIMEOUT,
    MAX_RESPONSE_LENGTH,
    STORAGE_DIR,
    CHROMA_COLLECTION_NAME,
    LOG_LEVEL,
    LOG_FORMAT
)

__all__ = [
    "TELEGRAM_TOKEN",
    "OLLAMA_MODEL",
    "EMBEDDING_MODEL",
    "LLM_REQUEST_TIMEOUT",
    "LLM_TEMPERATURE",
    "LLM_CONTEXT_WINDOW",
    "LLM_NUM_CTX",
    "SIMILARITY_TOP_K",
    "SIMILARITY_CUTOFF",
    "QUERY_TIMEOUT",
    "MAX_RESPONSE_LENGTH",
    "STORAGE_DIR",
    "CHROMA_COLLECTION_NAME",
    "LOG_LEVEL",
    "LOG_FORMAT"
]